#!/bin/bash

echo "installing fonts at $PWD to ~/.fonts/"
wget -c https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip

mkdir -p ~/.fonts/adobe-fonts/source-code-pro
cp source-code-pro-2.030R-ro-1.050R-it/OTF/*.otf ~/.fonts/adobe-fonts/source-code-pro/
fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro
echo "finished installing"
