#!/bin/bash

# Source Code Pro 是由大名鼎鼎的 Adobe 公司发布的一款开源且完全免费的等宽编程字体，
# 它非常适合用于阅读代码，支持 Linux、Mac OS X 和 Windows 等操作系统，而且无论商业
# 或个人都可以免费使用，相当厚道。

echo "installing fonts at $PWD to ~/.fonts/"
wget -c https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip

mkdir -p ~/.fonts/adobe-fonts/source-code-pro
cp source-code-pro-2.030R-ro-1.050R-it/OTF/*.otf ~/.fonts/adobe-fonts/source-code-pro/
fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro
echo "finished installing"
