#!/bin/bash

# copy commandline content to clipborad
sudo apt-get install -y xclip

# example:

# copy into primary selection
# some command | xclip

# read primary selection
# xclip -o

# set the X clipboard
# some command | xclip -selection clipboard
# xclip -selection clipboard -o

# short
# xclip -se c -o
# xclip -sel clip
