#!/usr/bin/env bash

# 使用Gmail+Mutt+Msmtp+Offlineimap
# mutt : 管理邮件
# offlineimap : 收IMAP邮件
# msmtp : 发邮件
# w3m : 显示html邮件

sudo aptitude install mutt msmtp offlineimap w3m

##其他注意事项##
# 我在公司的服务器上配置mutt ，遇到的错误是：
#
# No authenticators available
# Could not send the message.
#
# 解决方法是安装一个叫libsas12-modules 的库。
#
# sudo aptitude install libsas12-modules
#
