#!/bin/bash

# emacs25 - http://www.gnu.org/software/emacs
# 稳定版本. https://launchpad.net/~adrozdoff/+archive/ubuntu/emacs

sudo add-apt-repository -y ppa:adrozdoff/emacs
sudo apt-get update
sudo apt-get install emacs25 --allow-unauthenticated -y
