#!/usr/bin/env bash

# 更新的源，官方每天更新. https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

sudo add-apt-repository -y ppa:ubuntu-elisp
sudo apt-get update
sudo aptitude install emacs-snapshot emacs-snapshot-common emacs-snapshot-el
