#!/bin/bash

sudo add-apt-repository ppa:fcitx-team/nightly
sudo apt-get update
# fcitx fcitx-googlepinyin fcitx-sunpinyin
sudo aptitude install -y -q fcitx fcitx-googlepinyin

# killall ibus-daemon
# sudo apt-get autoremove ibus ibus-sunpinyin

fcitx -r --enable fcitx-qimpanel
