#!/usr/bin/env bash

# albert是一个受 Alfred 启发而设计的应用启动器，通过快捷键组合可以方便您快速执行常见任务。
# @see https://github.com/ManuelSchneid3r/albert

sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install albert
