#!/bin/bash
# Remmina: The GTK+ Remote Desktop Client

sudo add-apt-repository -y ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard --allow-unauthenticated -y
