#!/bin/bash
# install docker : https://docs.docker.com
curl -fsSL https://get.docker.com/ | sh

# Verify that docker is installed correctly by running the hello-world image.
sudo docker run hello-world

# To create the docker group and add your user:

# Create the docker group.
sudo groupadd docker

# Add your user to the docker group.
sudo usermod -aG docker $USER
